import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "NoTrace Feedback",
  description: "Generated by create next app",
};

export default async function FeedbacksSectionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
