import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Link from "next/link";
import Footer from "@/components/custom/Footer";
import AnimateText from "@/components/custom/animations/AnimateText";

export const metadata: Metadata = {
  title: "NoTrace Feedback",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";


export default async function RootLayout({
  FeedbackCategoryLinks,
  FeedbacksSection,
}: Readonly<{
  FeedbackCategoryLinks: React.ReactNode;
  FeedbacksSection: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (!session?.user || !session?.user?._id) {
    return <Link href={"/signin"}>Sign in</Link>;
  }

  return (
    <>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 bg-gradient-to-bl from-neutral-700/5 dark:from-white/5 via-background to-secondary/10">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 mt-8">
          <div className="py-8">
            <AnimateText className="text-6xl font-bold mb-2 " isHeading={true}>Dashboard</AnimateText>
            <AnimateText className="text-muted-foreground">
              Manage your feedback links and view responses
            </AnimateText>
          </div>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {FeedbackCategoryLinks}
          {FeedbacksSection}
        </div>
      </div>
      <Footer />
    </>
  );
}
