import type { Metadata } from "next";
import { dehydrate } from "@tanstack/react-query";
import getQueryClient from "@/lib/getQueryClient";
import ReactQueryProvider from "@/context/ReactQueryProvider";
import { getInitialFeedbacks } from "@/actions/getInitialFeedbackdata";
import { InitialFeedbacksType } from "@/types/InitailFeedbacksTypes";

export const metadata: Metadata = {
  title: "NoTrace Feedback",
  description: "Generated by create next app",
};

export default async function FeedbacksSectionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();

  await queryClient.prefetchInfiniteQuery({
    queryKey: [
      "feedbacks",
      { categoryId: "All Categories", type: "All Types" },
    ],
    queryFn: () => getInitialFeedbacks(),
    initialPageParam: 1,
    getNextPageParam: (lastPage: InitialFeedbacksType | undefined) => lastPage?.nextPage,
  });
  const dehydratedState = dehydrate(queryClient);

  return (
    <div>
      <ReactQueryProvider state={dehydratedState}>
        {children}
      </ReactQueryProvider>
    </div>
  );
}
